### ISSUE TITLE
How execute the frontend?

### ISSUE THREAD

**Issue by damianlluch** [muhammed-farghali/todo-laravel-vue#2]
Hi! thanks for sharing this resources.
I have a question, how execute the frontend with Laravel-mix ? I tried with the commands that exist in package.json, but I don't know what port is runnig  the app

thanks

**Comment by farghaliii** [comment]
Hi Damian,

This repo for API only does not have any frontend stuff, This repo. [ToDo](https://github.com/farghalii/learn-vue/tree/master/todo) for frontend but anyway I'm not working on it now, It was for practice.

Have a good day.
